//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSalesManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_item_m
    {
        public inventory_item_m()
        {
            this.inventory_item_price = new HashSet<inventory_item_price>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public int inventory_item_id { get; set; }
        public string description { get; set; }
        public int brand_id { get; set; }
        public int model_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string item_code { get; set; }
    
        public virtual model_m model_m { get; set; }
        public virtual ICollection<inventory_item_price> inventory_item_price { get; set; }
    }
}
