//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSalesManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_item_price
    {
        public decimal price { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int inventory_item_id { get; set; }
    
        public virtual inventory_item_m inventory_item_m { get; set; }
    }
}
